export const POST_CREATE_REQUEST = 'POST_CREATE_REQUEST';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';
export const POST_CREATE_FAIL = 'POST_CREATE_FAIL';

export const POST_ALL_REQUEST = 'POST_ALL_REQUEST';
export const POST_ALL_SUCCESS = 'POST_ALL_SUCCESS';
export const POST_ALL_FAIL = 'POST_ALL_FAIL';

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST_FAIL';

export const POST_UPDATE_REQUEST = 'POST_UPDATE_REQUEST';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';
export const POST_UPDATE_FAIL = 'POST_UPDATE_FAIL';
export const POST_UPDATE_RESET = 'POST_UPDATE_RESET';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_BY_USER = 'FETCH_POSTS_BY_USER';
export const POST_DELETE = 'POST_DELETE';
export const POST_UPDATE = 'POST_UPDATE';
export const POST_LIKE = 'POST_LIKE';

export const POST_ADD_COMMENT = 'POST_ADD_COMMENT';
export const POST_DELETE_COMMENT = 'POST_DELETE_COMMENT';
export const POST_EDIT_COMMENT = 'POST_EDIT_COMMENT';

export const GET_MY_POSTS = 'GET_MY_POSTS';
